Adding missing plugin information required for release
javaee/javax.enterprise.deploy pull request #3
Opened 2018-03-08 06:45 UTC by pranjal10

2018-03-20 06:21 UTC, vinayvishal approved these changes
Looks good.

2018-03-22 08:36 UTC, yaminikb requested changes

2018-03-22 08:36 UTC, yaminikb commented on pom.xml
> +                <artifactId>maven-gpg-plugin</artifactId>
add plugin version

2018-03-26 07:02 UTC, yaminikb approved these changes

2018-03-26 07:03 UTC, merged